config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :questions, only: [:new, :create, :show, :index] do
    resources :answers, only: [:new, :create, :update]
  end
  resources :votes
  resources :categories, only: :show
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :votes, as: :votable

  after_create :update_question_status if :is_first_answer?
  after_update do
    question.update_attribute(:status, 'best_answer_chosen') if self.is_best_answer?
  end

  include Votable

  validates :user, presence: true
  validates :body, presence: true,
                    length: { in: 10..1000 }

  def is_first_answer?
    question.answers.size = 1
  end

  def update_question_status
    question.set_as_has_answers
  end
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :category
  belongs_to :question
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :categorizations

  has_many :categorizations
  has_many :questions, through: :categorizations

  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  def slug_candidates
    [:name, [:name, :id]]
  end
end

app/models/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  included do
    has_many :votes, as: :votable
  end

  def vote_points
    votes.upvote.size - votes.downvote.size
  end

  def has_vote_from?(user)
    votes.find_by(user_id: user.id).present?
  end

  def has_upvote_from?(user)
    votes.upvote.find_by(user_id: user.id).present?
  end

  def has_downvote_from?(user)
    votes.downvote.find_by(user_id: user.id).present?
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  has_many :votes, as: :votable
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_one :best_answer, -> { where(is_best_answer: true) }, class_name: 'Answer'

  enum status: %w(unanswered has_answers best_answer_chosen)

  include Votable

  validates :user, presence: true
  validates :title, presence: true,
                    length: { in: 4..100 }
  validates :description, length: { maximum: 2000 }

  scope :recent_first, -> { order(created_at: :desc) }

  extend FriendlyId
    friendly_id :slug_candidates, use: [:slugged, :finders]

  def slug_candidates
    [:title, [:title, :id]]
  end

  def set_as_has_answers
    has_answers!
  end

  def set_to_best_answer_chosen
    best_answer_chosen!
  end

  def has_best_answer?
    best_answer.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers
  has_many :votes, as: :votable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def current_vote_for(votable)
    Vote.find_by(user: self, votable: votable)
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :votable, polymorphic: true

  enum value: %w(upvote downvote)
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_update_user, only: [:update]

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.user = current_user
    @answer.question = @question

    if @answer.save
      flash[:success] = "Answer posted sucessfully."
      redirect_to question_path(@answer.question)
    else
      render 'questions/show'
    end
  end

  def update
    @answer = Answer.find(params[:id])

    if @answer.update_attributes(params.require(:answer).permit(:is_best_answer))
      flash[:notice] = 'Answer updated!'
    else
      flash[:error] = 'Something went wrong.'
    end
    redirect_to question_path(@answer.question)
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def authorize_update_user
    @answer = Answer.find(params[:id])
    if current_user != @answer.question.user
      flash[:notice] = 'You are not allowed to do that.'
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.build(question_params)

    if @question.save
      flash[:success] = "Question posted sucessfully."
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end

  def index
    @questions = Question.recent_first.all
  end

  private

  def question_params
    params.require(:question).permit(:title, :description, category_ids: [])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
    @vote = Vote.new(vote_params)
    @vote.user = current_user

    if @vote.save
      @votable = @vote.votable
      render template: 'votes/refresh_votes'
    else
      respond_to do |format|
        format.html { render :back, notice: "failure"}
      end
    end
  end

  def destroy
    @vote = Vote.find(params[:id])
    if params[:vote][:votable_type] == 'Question'
      @votable = Question.find(params[:vote][:votable_id])
    elsif params[:vote][:votable_type] == 'Answer'
      @votable = Answer.find(params[:vote][:votable_id])
    end

    if @vote.destroy
      render template: 'votes/refresh_votes'
    end
  end

  def update
    @vote = Vote.find(params[:id])
    if @vote.update_attributes(vote_params)
      @votable = @vote.votable
      render template: 'votes/refresh_votes'
    end
  end

  private

  def vote_params
    params.require(:vote).permit(:value, :votable_type, :votable_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/views/answers/_answer.haml
.well{ id: "answer-#{answer.id}" }
  .row
    .col-xs-1.voting{ id: "answer-#{answer.id}-voting" }
      = render partial: 'votes/votes', locals: { votable: answer }
    .col-xs-11
      - if answer.is_best_answer
        %span.label.label-primary Best Answer!
      %p
        = markdown(answer.body)
      %p
        submitted by
        %strong
          = answer.user.username
        %small
          = time_ago_in_words(answer.created_at)
          ago

      - if current_user && current_user == answer.question.user && answer.question.has_answers?
        = button_to 'Award Best Answer',
                    question_answer_path(answer.question, answer,
                    answer: { is_best_answer: true }),
                    method: :put,
                    class: 'btn btn-primary'

app/views/categories/_category.haml
%span.label.label-default
  = link_to category_path(category) do
    = category.name

app/views/categories/show.haml
%ol.breadcrumb
  %li= link_to 'Questions', questions_path
  %li.active= @category.name

%h2= @category.name

= render @category.questions

app/views/home/index.html.erb
<div class="hero center-block">
  <a href="https://flic.kr/p/eZoB6G">
    <%= image_tag "hero.jpg", class: "img-responsive img-rounded center-block" %>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SnackOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Snack Overflow", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Ask", new_question_path %></li>
            <li class='dropdown'>
              <a href='#' class='dropdown-toggle' data-toggle='dropdown' role='button' aria-expanded='false'>
                Answer Questions
                <span class='caret'></span>
              </a>
              <ul class='dropdown-menu' role='menu'>
                <% Category.all.each do |category| %>
                  <li><%= link_to category.name, category_path(category) %> </li>
                <% end %>
                <li class='divider'></li>
                <li><%= link_to 'All Questions', questions_path %></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">

            <% if current_user %>
              <li class="dropdown user-links">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                  <%= current_user.username %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">#</a></li>
                  <li class="divider"></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
<footer class='page-footer'>
  <p>Made by Liz</p>

  <div>
    <a href="https://www.linkedin.com/in/lizvdk">
      <%= fa_icon "linkedin-square 2x" %>
    </a>

    <a href="https://github.com/lizvdk">
      <%= fa_icon "github 2x" %>
    </a>

    <a href="https://twitter.com/lizvdk">
      <%= fa_icon "twitter 2x" %>
    </a>
  </div>
</footer>
</html>

app/views/questions/_question.haml
.well
  = render question.categories
  %h3
    = link_to question.title, question_path(question)
  %blockquote
    %p= question.description
    %footer
      %cite
        = question.user.username
        #{time_ago_in_words(question.created_at)} ago

app/views/questions/index.haml
%h1
  Recent Questions

.row
  .col-sm-12.col-md-8
    #recent-questions
      = render(@questions)

app/views/questions/new.html.erb
<h1>Ask a Question</h1>

<%= simple_form_for @question do |f|%>
  <%= f.error_notification %>

  <%= f.input :title %>
  <%= f.input :description, label: "Additional details" %>
  <%= f.association :categories, as: :check_boxes, collection: Category.order('name ASC') %>
  <%= f.submit "Ask question" %>
<% end %>

app/views/questions/show.html.erb
<div id="question-<%=@question.id %>">
  <div class="row">
    <div class="col-xs-1 voting" id="question-<%= @question.id %>-voting">
      <%= render partial: 'votes/votes', locals: { votable: @question } %>
    </div>

    <div class="col-xs-11">
      <%= render @question.categories %>
      <h1><%= @question.title %></h1>
      <p class="asker">asked by
        <b><%= @question.user.username %></b>
        <small><%= time_ago_in_words(@question.created_at) %> ago</small>
      </p>
      <% if @question.description.present? %>
        <blockquote><%= markdown(@question.description) %></blockquote>
      <% end %>
    </div>
  </div>

  <div id="answers">
    <h3>Answers</h3>
    <% if @answers.present? %>
      <%= render(@answers) %>
    <% else %>
      <p> No answers yet. </p>
    <% end %>
  </div>

  <div id="new-answer">
    <% if current_user %>
      <%= simple_form_for [@question, @answer] do |f|%>
        <%= f.error_notification %>

        <%= f.input :body, label: "Answer" %>

        <%= f.submit "Submit answer" %>
      <% end %>
    <% else %>
      <p>Please sign in to answer this question.</p>

    <% end %>
  </div>
</div>

app/views/votes/_votes.html.erb
<%= render partial: 'votes/buttons/upvote', locals: { votable: votable } %>
<div class="vote-total">
  <%= votable.vote_points %>
</div>
<%= render partial: 'votes/buttons/downvote', locals: { votable: votable } %>

<script>
  $('.visitor').popover();
  $('.votable-creator').popover();
</script>

app/views/votes/buttons/_downvote.html.erb
<% if current_user %>
  <% if current_user == votable.user %>
    <!-- votable creator -->
    <a tabindex="0"
      class="votable-creator downvote disabled"
      role="button"
      data-toggle="popover"
      data-trigger="hover"
      data-content="You cannot vote for your own <%= votable.class.to_s.downcase %>.">
    </a>
  <% else %>
    <% if votable.has_vote_from?(current_user) %>
      <% if current_user.current_vote_for(votable).upvote? %>
        <!-- update vote: switch from up to down -->
        <div>
          <%= link_to "", vote_path(current_user.current_vote_for(votable),
                                    vote: {
                                      votable: votable,
                                      votable_type: votable.class,
                                      votable_id: votable.id,
                                      value: "downvote"
                                    }),
                            method: :put,
                            remote: :true,
                            class: "downvote" %>
        </div>

      <% elsif current_user.current_vote_for(votable).downvote? %>
        <!-- delete vote -->
        <div>
          <%= link_to "", vote_path(current_user.current_vote_for(votable),
                                    vote: {
                                      votable: votable,
                                      votable_type: votable.class,
                                      votable_id: votable.id,
                                    }),
                            method: :delete,
                            remote: :true,
                            class: "downvote voted" %>
        </div>
      <% end %>
    <% else %>
      <!-- create downvote -->
      <div>
        <%= link_to "", votes_path(vote: {
                                    votable: votable,
                                    votable_type: votable.class,
                                    votable_id: votable.id,
                                    value: "downvote"
                                  }),
                          method: :post,
                          remote: :true,
                          class: "downvote" %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <!-- unauthenticated visitor -->
  <a tabindex="0"
    class="visitor downvote disabled"
    role="button"
    data-toggle="popover"
    data-trigger="hover"
    data-content="You must sign in to downvote.">
  </a>
<% end %>

app/views/votes/buttons/_upvote.html.erb
<% if current_user %>
  <% if current_user == votable.user %>
    <!-- votable creator -->
    <a tabindex="0"
      class="votable-creator upvote disabled"
      role="button"
      data-toggle="popover"
      data-trigger="hover"
      data-content="You cannot vote for your own <%= votable.class.to_s.downcase %>.">
    </a>
  <% else %>
    <% if votable.has_vote_from?(current_user) %>
      <% if current_user.current_vote_for(votable).upvote? %>
        <!-- delete vote -->
        <div>
          <%= link_to "", vote_path(current_user.current_vote_for(votable),
                                    vote: {
                                      votable: votable,
                                      votable_type: votable.class,
                                      votable_id: votable.id,
                                    }),
                            method: :delete,
                            remote: :true,
                            class: "upvote voted" %>
        </div>
      <% elsif current_user.current_vote_for(votable).downvote? %>
        <!-- update vote: switch from down to up -->
        <div>
          <%= link_to "", vote_path(current_user.current_vote_for(votable),
                                    vote: {
                                      votable: votable,
                                      votable_type: votable.class,
                                      votable_id: votable.id,
                                      value: "upvote"
                                    }),
                            method: :put,
                            remote: :true,
                            class: "upvote" %>
        </div>
      <% end %>
    <% else %>
      <!-- create upvote -->
      <div>
        <%= link_to "", votes_path(vote: {
                                    votable: votable,
                                    votable_type: votable.class,
                                    votable_id: votable.id,
                                    value: "upvote"
                                  }),
                          method: :post,
                          remote: :true,
                          class: "upvote" %>
      </div>
    <% end %>
  <% end %>
<% else %>
  <!-- unauthenticated visitor -->
  <a tabindex="0"
    class="visitor upvote disabled"
    role="button"
    data-toggle="popover"
    data-trigger="hover"
    data-content="You must sign in to upvote.">
  </a>
<% end %>

app/views/votes/create.js.erb
<% votable_css_id = "#{@votable.class.to_s.downcase}-#{@votable.id}" %>

$("#<%= votable_css_id %>-voting").html("<%= escape_javascript (render partial: 'votes', locals: { votable: @votable} ) %>");

app/views/votes/refresh_votes.js.erb
<% votable_css_id = "#{@votable.class.to_s.downcase}-#{@votable.id}" %>

$("#<%= votable_css_id %>-voting").html("<%= escape_javascript (render partial: 'votes', locals: { votable: @votable} ) %>");